version: '3'
services:
  keycloak-latest:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=INFO
      - WILDFLY_LOGGING_FILE=stdout
    ports:
      - "8088:8080"
    restart: always

  keycloack:
    image: quay.io/keycloak/keycloak:12.0.2
    container_name: keycloak
    ports:
      - 8080:8080
      - 8443:8443
    restart: unless-stopped
    environment:
      # Credentials for admin account
      # -----------------------------
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"

      # Credentials for storing into an external database
      # -------------------------------------------------
      # DB_VENDOR: "mysql"
      # DB_ADDR: 
      # DB_PORT:
      # DB_DATABASE: 
      # DB_USER:
      # DB_PASSWORD: 
