version: "3.7"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD = root
      - REDIS_USER = user
    volumes:
      - ./tmp/redis:/data