version: '3'
services:
  gluu:
    image: gluufederation/community-edition:latest
    environment:
      - GLUU_ADMIN_PASS=admin
      - GLUU_AUTHENTICATION_MODE=oxAuth
    ports:
      - "8099:8080"
    restart: always
