version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: fusionauth
      POSTGRES_PASSWORD: fusionauth
      POSTGRES_DB: fusionauth
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USER: fusionauth
      DATABASE_ROOT_PASSWORD: fusionauth
    ports:
      - "9011:9011"
    restart: always
